INSERT INTO trivia (
    item_name,
    topic_level_1,
    topic_level_2,
    is_checked_fact,
    is_checked_voice,
    is_checked_hook,
    is_checked_interest,
    is_checked_conciseness,
    is_posted_question,
    is_posted_answer,
    is_staged_question,
    is_staged_answer,
    datetime_scheduled_question,
    datetime_scheduled_answer,
    datetime_posted_question,
    datetime_posted_answer,
    question_opener,
    question_raw,
    question_images_url,
    question_source_links_url,
    answer_raw,
    answer_notes,
    answer_links_url,
    question_post_link_urlstub,
    answer_post_link_urlstub
) VALUES (
    $$Knowledge Fragment 000002$$,
    $$Space$$,
    $$Gravitational Lensing$$,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    $$2026-04-04 23:00:00 America/New_York$$,
    $$2026-04-05 20:00:00 America/New_York$$,
    $$2026-04-04 23:00:00 America/New_York$$,
    $$2026-04-05 20:00:00 America/New_York$$,
    $$Here's our next question!$$,
    $$This phenomenon can make one distant star appear stretched or even duplicated in the sky. What is it?$$,
    null,
    null,
    $$Yesterday's answer: Gravitational lensing

    Gravity can bend light. When light from a distant star passes through extra strong gravity (like a galaxy or black hole), some of that light can be bent, making the star appear stretched, shifted, or even duplicated--like a galaxy-sized funhouse mirror!$$,
    null,
    $$https://lettersandsciencemag.ucdavis.edu/science-technology/gravitational-lenses-uc-davis-astronomy$$,
    $$2040630959020662815$$,
    $$2040942567060373618$$
), (
    $$Knowledge Fragment 000003$$,
    $$Space$$,
    $$Celestial Sizes$$,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    $$2026-04-05 21:00:00 America/New_York$$,
    $$2026-04-06 20:00:00 America/New_York$$,
    $$2026-04-05 21:00:00 America/New_York$$,
    $$2026-04-06 20:00:00 America/New_York$$,
    $$Hope you're ready--our next question is here!$$,
    $$Parallax is the shift in an object's apparent position when viewed from two locations. Around 190 BCE, it was famously used to estimate the distance to what object in space?$$,
    null,
    null,
    $$Yesterday's answer: The Moon

    Ancient astronomer Hipparchus used parallax during a solar eclipse & geometry to estimate the Moon's distance from Earth--thousands of years before telescopes or calculators existed!$$,
    null,
    $$https://archive.nyu.edu/bitstream/2451/61288/56/11.%20Carman.pdf$$,
    $$2040957664818311403$$,
    $$2041304951150829817$$
), (
    $$Knowledge Fragment 000004$$,
    $$Space$$,
    $$Auroras$$,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    TRUE,
    TRUE,
    $$2026-04-06 21:00:00 America/New_York$$,
    $$2026-04-07 20:00:00 America/New_York$$,
    $$2026-04-06 21:00:00 America/New_York$$,
    null,
    null,
    $$During extreme solar storms, the northern lights can appear far beyond the Arctic. What is the farthest south they've ever been recorded?$$,
    null,
    null,
    $$Yesterday's answer: Columbia, South America

    In 1859, the most powerful recorded solar storm lit the sky so intensely that the Northern Lights reached as far south as Colombia, near the equator! Telegraph systems sparked, caught fire, and in some cases kept sending messages even after power was disconnected.

    Talk about a shocking fact, eh?$$,
    null,
    $$https://arxiv.org/abs/1508.06365$$,
    $$2041327572911374662$$,
    null
), (
    $$Knowledge Fragment 000005$$,
    $$Space$$,
    $$Telescopes$$,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    $$2026-04-07 21:00:00 America/New_York$$,
    $$2026-04-08 20:00:00 America/New_York$$,
    null,
    null,
    $$Another trivia question, right on time!$$,
    $$If you used a yearly calendar on Venus, how many days would appear on that calendar?$$,
    null,
    null,
    $$Yesterday's answer: less than one!

    A single day on Venus lasts longer than its entire year. The planet spins so slowly that it completes an orbit around the Sun before one full day is even finished.

    That means you'd celebrate New Year's Day every day, and some days even twice!$$,
    null,
    $$https://www.space.com/venus-atomphere-slows-down-rotation$$,
    null,
    null
), (
    $$Knowledge Fragment 000006$$,
    $$Space$$,
    $$Solar Eclipses$$,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    $$2026-04-08 21:00:00 America/New_York$$,
    $$2026-04-09 20:00:00 America/New_York$$,
    null,
    null,
    null,
    $$Total solar eclipses happen somewhere on Earth every couple of years. But at any one location, how often do they happen on average?$$,
    null,
    null,
    $$Yesterday's answer: roughly every 366 years

    A total solar eclipse happens somewhere on Earth about every 18 months, but the path shifts each time. If you stayed in one place waiting for the next one, you'd likely be waiting for centuries!$$,
    null,
    $$https://www.thesuntoday.org/eclipses/solar/total/$$,
    null,
    null
), (
    $$Knowledge Fragment 000007$$,
    $$Space$$,
    $$Space Travel$$,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    TRUE,
    FALSE,
    FALSE,
    TRUE,
    TRUE,
    $$2026-04-09 21:00:00 America/New_York$$,
    $$2026-04-10 20:00:00 America/New_York$$,
    null,
    null,
    null,
    $$After crossing beyond our solar system, Voyager 1 discovered something completely unexpected near its outer edge. What was it?$$,
    null,
    null,
    $$Yesterday's answer: A wall of fire

    Many people believed interstellar space is empty and calm--including most scientists, until recently. After Voyager 1 exited our solar system, it had an unexpected encounter with a superheated wall of plasma, reaching upwards of 50,000 C--nearly 10 times hotter than the surface of the Sun!$$,
    null,
    $$https://www.bgr.com/1984386/nasa-voyager-1-discovery-wall-of-fire/$$,
    null,
    null
);